baseURL: "https://907.life/"
title: "907.life"
theme: "PaperMod"

# Basic Configuration
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# Site Params for PaperMod
params:
  env: production
  title: "907.life"
  description: "Geoff Wright's personal blog"
  author: "Geoff Wright"
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowWordCount: true
  UseHugoToc: true
  Social:
    - name: Bluesky
      url: "https://bsky.app/profile/glw907"
    - name: GitHub
      url: "https://github.com/glw907"
    - name: LinkedIn
      url: "https://linkedin.com/in/geoffreywright"

# Taxonomies (Categories and Tags)
taxonomies:
  category: "categories"
  tag: "tags"

# Menu Configuration
menu:
  main:
    - name: "About"
      url: "/about/"
      weight: 10
    - name: "Archives"
      url: "/archives/"
      weight: 20
    - name: "Categories"
      url: "/categories/"
      weight: 30
    - name: "Contact"
      url: "/contact/"
      weight: 40

# Syntax Highlighting (Pygments)
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false