base  URL: “https://907.life/“
title: "907.life"
theme: "PaperMod"

# Basic Configuration
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

# Site Params for PaperMod
params:
  env: production
  title: "907.life"
  description: "Geoff Wright's personal blog"
  author: "Geoffrey L. Wright"
  defaultTheme: auto
  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowWordCount: true
  UseHugoToc: true
  socialIcons:
    - name: rss
      url: "/index.xml"  # Path to your RSS feed
    - name: bluesky
      url: "https://bsky.app/profile/glw907"  # Replace with your Bluesky handle
    - name: linkedin
      url: "https://www.linkedin.com/in/geoffreywright/" 

# Output formats, including RSS
outputs:
  home:
    - HTML
    - RSS
    - JSON 

# Taxonomies (Categories and Tags)
taxonomies:
  category: "categories"
  tag: "tags"

# Look for posts in the /posts/ directory, and use friendly URLs
permalinks:
  posts: "/:year/:month/:title/"

# Menu Configuration
menu:
  main:
    - name: "About"
      url: "/about/"
      weight: 10
    - name: "Archives"
      url: "/archives/"
      weight: 20
    - name: "Categories"
      url: "/categories/"
      weight: 30
    - name: "Contact"
      url: "/contact/"
      weight: 40

# Syntax Highlighting (Pygments)
pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false