name: Deploy Hugo site to GitHub Pages

on:
  push:
    branches:
      - main # Watches the main branch for changes
      - content/** # Watches the content directory for changes

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        submodules: recursive # Ensures submodules like PaperMod are pulled recursively

    - name: Ensure Hugo directory structure
      run: |
        mkdir -p archetypes content data layouts static themes

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest' # Specify version or keep 'latest'

    - name: Build site
      run: hugo --minify # Minifies for optimized site

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub provides this automatically
        publish_dir: ./public # Directory Hugo outputs to
        publish_branch: gh-pages # Branch serving the site on GitHub Pages